databases:
  - name: db
    plan: free
    databaseName: skillup-db
    user: postgres

services:
  - type: web
    plan: free
    name: skillup
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn skillup.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: skillup-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4